# Generated by Django 4.2 on 2023-06-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calldata',
            name='data',
        ),
        migrations.AddField(
            model_name='calldata',
            name='current_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='calldata',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='calldata',
            name='symbol',
            field=models.TextField(null=True),
        ),
    ]
