# Generated by Django 4.2 on 2023-06-24 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_alter_calldata_name_alter_calldata_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='calldata',
            name='upload_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='calldata',
            name='symbol',
            field=models.TextField(null=True),
        ),
    ]
