# Generated by Django 4.2 on 2023-06-24 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0008_alter_calldata_current_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_range', models.DecimalField(decimal_places=6, default=1, max_digits=10)),
                ('max_range', models.DecimalField(decimal_places=6, default=1, max_digits=10)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranges', to='hub.calldata')),
            ],
        ),
    ]
