# Generated by Django 4.2 on 2023-06-24 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0009_ranges'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ranges',
        ),
    ]
