# Generated by Django 4.2 on 2023-06-24 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0011_alter_calldata_current_price_ranges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranges',
            name='symbol',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ranges', to='hub.calldata'),
        ),
    ]
