# Generated by Django 4.2 on 2023-06-26 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0012_alter_ranges_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='calldata',
            name='high_24h',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='calldata',
            name='low_24h',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='calldata',
            name='market_cap',
            field=models.DecimalField(decimal_places=10, max_digits=50, null=True),
        ),
        migrations.AddField(
            model_name='calldata',
            name='price_change_percentage_24h',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
    ]
