# Generated by Django 4.2 on 2023-06-26 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0013_calldata_high_24h_calldata_low_24h_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calldata',
            name='market_cap_rank',
            field=models.IntegerField(null=True),
        ),
    ]
