# Generated by Django 4.2 on 2023-07-19 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0019_alter_ranges_coin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranges',
            name='coin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ranges', to='hub.coin'),
        ),
    ]
