# Generated by Django 4.2 on 2023-10-28 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0020_alter_ranges_coin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranges',
            name='max_range',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='ranges',
            name='min_range',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True),
        ),
    ]
