# Generated by Django 4.2 on 2023-10-28 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0021_alter_ranges_max_range_alter_ranges_min_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='history_price',
            field=models.TextField(null=True),
        ),
    ]
