# Generated by Django 4.2 on 2023-11-02 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0022_coin_history_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='upload_time',
            field=models.TextField(null=True),
        ),
    ]
