# Generated by Django 4.2 on 2023-11-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0023_alter_coin_upload_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='cg_identifier',
            field=models.TextField(null=True),
        ),
    ]
