# Generated by Django 5.0 on 2023-12-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0025_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='private_history_price',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='private_upload_time',
            field=models.TextField(null=True),
        ),
    ]
