# Generated by Django 5.0 on 2024-01-03 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0026_coin_private_history_price_coin_private_upload_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranges',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_ranges', to='hub.user'),
            preserve_default=False,
        ),
    ]
