# Generated by Django 5.0 on 2024-01-08 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0033_remove_ranges_user_alter_ranges_coin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranges',
            name='coin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranges', to='hub.coin'),
        ),
    ]
