# Generated by Django 5.0 on 2024-01-08 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0037_ranges_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ranges',
            name='user',
        ),
    ]
